name: hook_deliveryprueba
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.10.0
  mobile_scanner: ^7.0.1
  http: ^1.5.0
  intl: ^0.20.2
  timezone: ^0.10.1
  provider: ^6.1.5+1
  flutter_launcher_icons: ^0.14.4
  cupertino_icons: ^1.0.8
  connectivity_plus: ^7.0.0
  url_launcher: ^6.3.2
  shared_preferences: ^2.5.3
  google_maps_flutter: ^2.13.1
  geolocator: ^14.0.2
  speech_to_text: ^7.3.0
  open_filex: ^4.7.0
  printing: ^5.14.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/mx_flag.png
    - assets/us_flag.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  